### ISSUE TITLE
自己在vps上用docker做了部署，前面用npm套了一层后，搜索没结果

### ISSUE THREAD

**Issue by poctopus** [LibreSpark/LibreTV#107]
在dpanel中做部署，并且将config.js文件映射出来，直接用9988端口访问，可以搜索，可以播放，但是用npm套的域名就无法搜索了。
```
version: '3'
services:
  libretv:
    image: bestzwei/libretv:latest
    container_name: libretv
    ports:
      - "9988:80"
    volumes:
      - /app/libretv/config.js:/usr/share/nginx/html/js/config.js
    restart: unless-stopped
```
